### ISSUE TITLE
For "add" let user focus on a certain type of media

### ISSUE THREAD

**Issue by bryanph** [bryanph/Geist#90]
So instead of just adding rich text you add a certain type of media as a focus (so that later the UI can be changed to accommodate different types of media).
- [ ] Rich text
- [ ] Video
- [ ] Image
- [ ] Audio
- [ ] Resource (like a pdf, website?)

**Comment by erros84** [comment]
DITA may be a "media" format may be almost as relevant as rich text, as it contains some of the same elements. 
https://www.learningsolutionsmag.com/articles/524/what-is-dita-and-why-should-you-care

My Use case:
I work in Language Technology, supporting linguists who work with minority languages. I daily run into situations where I want to store and recall bits of data, whether it be steps to resolve a problem, useful resources, or interesting articles.
Often, I may want to generate a PDF combining some of these items to share with someone.
The metadata of DITA allows one to define things like links, version numbers, environment, audience, dates, etc, so that I can powerfully bag and tag these items, but I wanted a graph storage system to show the links and help me organize.

**Comment by bryanph** [comment]
That is in interesting use case @erros84. I am working on a redesign in this branch https://github.com/bryanph/Geist/tree/feature/redesign and am for now focusing on rich text to avoid over-complication. However, I suppose this could be generalized at a later date to more ouput formats like the one you propose.

**Comment by erros84** [comment]
After further research, DITA is a powerful schema with a restrictive workflow, and focusing on Markdown. Would it be very disruptive to put this in there: https://www.npmjs.com/package/draft-js-markdown-shortcuts-plugin ?

**Comment by bryanph** [comment]
I like the plugin, I'll see if I can integrate it

2017-08-04 3:20 GMT+02:00 erros84 <notifications@github.com>:
